#!/usr/bin/env bash
# Resync portal/src/postern/static/flags/ from lipis/flag-icons at a pinned tag.
#
# Idempotent: safe to re-run; replaces all svgs and regenerates flags.css.
# Network access (git clone over HTTPS) is required.
#
# Bumping the pinned tag:
#   1. Update FLAG_ICONS_TAG below
#   2. Run this script
#   3. Inspect the diff (`git status portal/src/postern/static/flags/`); commit
#      with a conventional-commit subject like `chore(portal): bump flag-icons to vX.Y.Z`.

set -euo pipefail

FLAG_ICONS_TAG="v7.5.0"   # https://github.com/lipis/flag-icons/releases
FLAG_ICONS_REPO="https://github.com/lipis/flag-icons.git"

script_dir="$(cd "$(dirname "$0")" && pwd)"
target_dir="${script_dir}/../src/postern/static/flags"
tmp_dir="$(mktemp -d)"
trap 'rm -rf "${tmp_dir}"' EXIT

echo "Cloning ${FLAG_ICONS_REPO} at ${FLAG_ICONS_TAG} into ${tmp_dir}..."
git clone --depth 1 --branch "${FLAG_ICONS_TAG}" "${FLAG_ICONS_REPO}" "${tmp_dir}/flag-icons" >/dev/null

mkdir -p "${target_dir}"
# Wipe any prior contents so removals upstream propagate.
find "${target_dir}" -maxdepth 1 -type f \( -name '*.svg' -o -name '*.css' \) -delete

echo "Copying alpha-2 country flags (4x3, lowercase filenames)..."
shopt -s nullglob
src="${tmp_dir}/flag-icons/flags/4x3"
count=0
for f in "${src}"/[a-z][a-z].svg; do
    base="$(basename "${f}")"
    cp "${f}" "${target_dir}/${base}"
    count=$((count + 1))
done
shopt -u nullglob

echo "Generating flags.css..."
css="${target_dir}/flags.css"
{
    echo "/* Auto-generated by portal/scripts/sync-flags.sh from lipis/flag-icons ${FLAG_ICONS_TAG} -- do not edit */"
    for f in "${target_dir}"/*.svg; do
        name="$(basename "${f}" .svg)"
        printf '.flag-%s { background-image: url("/static/flags/%s.svg"); }\n' "${name}" "${name}"
    done
} > "${css}"

echo "Done: ${count} flags + flags.css at ${target_dir}"
