#!/bin/sh
# Render nginx config templates from environment. Sourced by nginx-entrypoint.sh
# and exercised directly by portal/tests/test_nginx_render.py.
#
# Honors:
#   DOMAIN              (required) -- substituted for ${DOMAIN} in *.tmpl files.
#   PROXY_PROTOCOL_FROM (optional) -- when set, nginx accepts PROXY protocol v2
#                       from the listed CIDR(s) and recovers the real client IP.
#                       Comma/whitespace-separated. When unset/empty the rendered
#                       config is byte-for-byte identical to pre-#98 behavior.
#
# TEMPLATE_DIR / TARGET_DIR default to the in-image paths but are overridable so
# the unit test can render into a temp dir without a container. Defines functions
# only; running the render is the caller's job (entrypoint or test).

render_templates() {
	template_dir="${TEMPLATE_DIR:-/etc/nginx/templates}"
	target_dir="${TARGET_DIR:-/etc/nginx}"

	if [ ! -d "$template_dir" ]; then
		echo "render: no templates at $template_dir; nothing to render" >&2
		return 0
	fi
	if [ -z "${DOMAIN:-}" ]; then
		echo "render: DOMAIN must be set (templates at $template_dir require it)" >&2
		return 1
	fi

	# Proxy-protocol gating. ${PROXY_PROTOCOL_LISTEN} is substituted into the
	# listen lines; the real-ip directives go into a generated include that is
	# always written (empty when disabled, so the include always resolves).
	if [ -n "${PROXY_PROTOCOL_FROM:-}" ]; then
		proxy_protocol_listen=" proxy_protocol"
	else
		proxy_protocol_listen=""
	fi
	_write_real_ip_conf "$target_dir" || return 1

	# Collect sources into a filelist first so the loop runs in THIS shell. A
	# `find | while` would put the loop body in a subshell, where a `return` on a
	# genuine render failure could not abort the function (busybox/dash). The
	# filelist lives under target_dir, which is writable in every deployment.
	filelist="$target_dir/.render-filelist.$$"
	find "$template_dir" -type f >"$filelist" || { rm -f "$filelist"; return 1; }

	rc=0
	while IFS= read -r src; do
		rel=${src#"$template_dir"/}
		case "$rel" in
			*.tmpl) dst="$target_dir/${rel%.tmpl}"; is_tmpl=1 ;;
			*) dst="$target_dir/$rel"; is_tmpl=0 ;;
		esac
		mkdir -p "$(dirname "$dst")" 2>/dev/null || true
		tmp="$dst.tmp.$$"
		# Render into $tmp (always in the writable target dir). A failure HERE is a
		# genuine error -> fail loudly so the container won't start on a bad config.
		if [ "$is_tmpl" = 1 ]; then
			if ! sed -e "s|\${DOMAIN}|$DOMAIN|g" \
			         -e "s|\${PROXY_PROTOCOL_LISTEN}|$proxy_protocol_listen|g" \
			         "$src" >"$tmp"; then
				echo "render: FATAL -- failed to render $src" >&2
				rm -f "$tmp"; rc=1; break
			fi
		else
			if ! cp "$src" "$tmp"; then
				echo "render: FATAL -- failed to copy $src" >&2
				rm -f "$tmp"; rc=1; break
			fi
		fi
		# The mv may fail when $dst is a read-only bind mount (the e2e suite mounts
		# its own nginx.conf over the rendered one). That is expected and tolerated
		# -- the bind-mounted file wins; the successful render above proves the
		# config itself is sound.
		if mv -f "$tmp" "$dst" 2>/dev/null; then
			echo "render: rendered $dst" >&2
		else
			rm -f "$tmp"
			echo "render: skipped $dst (target read-only)" >&2
		fi
	done <"$filelist"
	rm -f "$filelist"
	return "$rc"
}

# Write <target>/conf.d/real_ip.conf. Empty file when PROXY_PROTOCOL_FROM is
# unset; otherwise the realip directives, one set_real_ip_from per CIDR. This
# file is generated (never a read-only bind mount) and is `include`d by
# nginx.conf, so any write/install failure is fatal -- a missing include would
# crash nginx at start.
_write_real_ip_conf() {
	target_dir="$1"
	dst="$target_dir/conf.d/real_ip.conf"
	mkdir -p "$target_dir/conf.d" 2>/dev/null || true
	tmp="$dst.tmp.$$"
	if [ -n "${PROXY_PROTOCOL_FROM:-}" ]; then
		if ! {
			echo "# Generated by render.sh from PROXY_PROTOCOL_FROM -- do not edit."
			echo "real_ip_header proxy_protocol;"
			echo "real_ip_recursive on;"
			echo "$PROXY_PROTOCOL_FROM" | tr ', \t' '\n\n\n' | while read -r cidr; do
				if [ -n "$cidr" ]; then echo "set_real_ip_from $cidr;"; fi
			done
		} >"$tmp"; then
			echo "render: FATAL -- failed to write $dst" >&2
			rm -f "$tmp"; return 1
		fi
	else
		if ! printf '' >"$tmp"; then
			echo "render: FATAL -- failed to write $dst" >&2
			rm -f "$tmp"; return 1
		fi
	fi
	if mv -f "$tmp" "$dst" 2>/dev/null; then
		return 0
	fi
	rm -f "$tmp"
	echo "render: FATAL -- failed to install $dst" >&2
	return 1
}
